src/ISZR.Web/Models/Permission.cs
using System.ComponentModel.DataAnnotations;

namespace ISZR.Web.Models
{
    /// <summary>
    /// Jogosultság
    /// </summary>
    public class Permission
    {
        /// <summary>
        /// Jogosultság azonosítója
        /// </summary>
        public int PermissionId { get; set; }

        /// <summary>
        /// Jogosultság neve
        /// </summary>
        [Display(Name = "Jogosultság megnevezése")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "A jogosultság megnevezése kötelező!")]
        [MinLength(3, ErrorMessage = "A jogosultság neve nem lehet kevesebb mint 3 karakter")]
        [MaxLength(64, ErrorMessage = "A jogosultság neve nem lehet nagyobb mint 64 karakter")]
        public string? Name { get; set; }

        /// <summary>
        /// Jogosultság típusa
        /// </summary>
        [Display(Name = "Jogosultság típusa")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "A típus kiválasztása kötelező!")]
        public string? Type { get; set; }

        /// <summary>
        /// Jogosultság leírása
        /// </summary>
        [Display(Name = "Jogosultság leírása")]
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "A jogosultság leírásának megadása kötelező!")]
        [MinLength(5, ErrorMessage = "A jogosultság leírásának legalább 5 karakter hosszúnak kell lennie!")]
        public string? Description { get; set; }

        /// <summary>
        /// Active Directory jogosultságok
        /// </summary>
        [Display(Name = "Active Directory jogosultságok")]
        [DataType(DataType.MultilineText)]
        public string? ActiveDirectoryPermissions { get; set; }

        /// <summary>
        /// Archiválva
        /// </summary>
        [Display(Name = "Archiválva")]
        public bool IsArchived { get; set; } = false;

        /// <summary>
        /// Jogosultság csoportjai
        /// </summary>
        public ICollection<GroupPermission> GroupPermissions { get; set; } = new List<GroupPermission>();
    }
}

src/ISZR.Web/Controllers/PermissionsController.cs
using ISZR.Web.Models;
using ISZR.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.Linq;

namespace ISZR.Web.Controllers
{
    /// <summary>
    /// /Permissions/? Controller
    /// </summary>
    [Authorize(Policy = "Administrator")]
    public class PermissionsController : Controller
    {
        private readonly DataContext _context;

        public PermissionsController(DataContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Jogosultságok listájának megjelenítése
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index(string name, string type, bool status, int? pageNumber)
        {
            // Értékek beállítása
            ViewData["name"] = name;
            ViewData["type"] = type;
            ViewData["status"] = status;

            // Jogosultságok listájának lekérdezése
            var dataContext = _context.Permissions
                .OrderBy(p => p.Name)
                .AsQueryable();

            // Státusz alapú szűrés
            if (status)
            {
                dataContext = dataContext.Where(r => !r.IsArchived);
            }
            else
            {
                dataContext = dataContext.Where(r => r.IsArchived);
            }

            // Típus alapú szürés
            if (!string.IsNullOrEmpty(type) && type != "Mind")
            {
                dataContext = dataContext.Where(r => r.Type == type);
            }

            // Név alapú szürés
            if (!string.IsNullOrEmpty(name))
            {
                dataContext = dataContext.Where(r => r.Name.Contains(name));
            }

            // Igénylési lista összeállítása
            await dataContext.ToListAsync();
            ViewData["dataLength"] = dataContext.Count();

            // Típus lista összeállítása
            List<string?> requestTypes = _context.Permissions.Select(r => r.Type).Distinct().OrderBy(r => r).ToList();
            requestTypes.Insert(0, "Mind");

            ViewData["TypeList"] = requestTypes.Select(type => new SelectListItem
            {
                Text = type,
                Value = type
            }).ToList();

            // Felület megjelenítése a kért listával
            return View(await PaginatedList<Permission>.CreateAsync(dataContext, pageNumber ?? 1));
        }

        /// <summary>
        /// Jogosultság archiválási állapotának megváltoztatása
        /// </summary>
        /// <param name="id">Jogosultság azonosítója</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(int? pageNumber, int? id)
        {
            // Azonosító meglétének ellenőrzése
            if (id == null || _context.Permissions == null) return NotFound();

            // Jogosultság megkeresése az adatbázisban
            var permission = await _context.Permissions
                .FirstOrDefaultAsync(m => m.PermissionId == id);

            // Jogosultság meglétének ellenőrzése
            if (permission == null) return NotFound();

            try
            {
                // Archiválás értékének módosítása
                permission.IsArchived = !permission.IsArchived;

                // Jogosultság értékeinek frissítése az adatbázisban
                _context.Update(permission);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PermissionExists(permission.PermissionId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            // Felület újra megjelenítése
            return RedirectToAction(nameof(Index), new { status = !permission.IsArchived });
        }

        /// <summary>
        /// Adott jogosultság értékeinek megjelenítése
        /// </summary>
        /// <param name="id">Jogosultság azonosítója</param>
        public async Task<IActionResult> Details(int? id)
        {
            // Azonosítók meglétének ellenőrzése
            if (id == null || _context.Permissions == null) return NotFound();

            // Jogosultság megkeresése az adatbázisban
            var permission = await _context.Permissions.FirstOrDefaultAsync(m => m.PermissionId == id);

            // Jogosultság meglétének ellenőrzése
            if (permission == null) return NotFound();

            // Felület megjelenítése a kért osztály értékeivel
            return View(permission);
        }

        /// <summary>
        /// Jogosultság létrehozásának felülete
        /// </summary>
        /// <param name="type">Jogosultsági típus</param>
        public IActionResult Create(string? type)
        {
            // Típus meglétének ellenőrzése
            if (type == null) return NotFound();

            // Típus beállítása
            ViewData["type"] = type;

            // Felület megjelenítése típus alapján
            return View();
        }

        /// <summary>
        /// Jogosultság létrehozása az adatbázisban
        /// </summary>
        /// <param name="permission">Jogosultság új értékei</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PermissionId,Name,Type,Description,ActiveDirectoryPermissions,IsArchived")] Permission permission)
        {
            // Megadott értékek ellenőrzése
            if (ModelState.IsValid)
            {
                try
                {
                    // Jogosultság hozzáadása az adatbázishoz
                    _context.Add(permission);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PermissionExists(permission.PermissionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                // Felhasználó átírányítása a jogosultságok listájához
                return RedirectToAction(nameof(Index), new { status = true });
            }

            // Felület újra megjelenítése, amennyiben a megadott értékek hibásak
            return View(permission);
        }

        /// <summary>
        /// Jogosultság értékeinek szerkesztésének felülete
        /// </summary>
        /// <param name="id">Jogosultsági azonosító</param>
        public async Task<IActionResult> Edit(int? id)
        {
            // Azonosító meglétének ellenőrzése
            if (id == null || _context.Permissions == null) return NotFound();

            // Jogosultság megkeresése az adatbázisban
            var permission = await _context.Permissions.FindAsync(id);

            // Jogosultság meglétének ellenőrzése
            if (permission == null) return NotFound();

            // Felület megjelenítése a kért jogosultság értékeivel
            return View(permission);
        }

        /// <summary>
        /// Jogosultság értékeinek szerkesztése az adatbázisban
        /// </summary>
        /// <param name="id">Jogosultsági azonosító</param>
        /// <param name="permission">Jogosultság új értékei</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PermissionId,Name,Type,Description,ActiveDirectoryPermissions,IsArchived")] Permission permission)
        {
            // Azonosító meglétének ellenőrzése
            if (id != permission.PermissionId) return NotFound();

            // Megadott értékek ellenőrzése
            if (ModelState.IsValid)
            {
                try
                {
                    // Jogosultság értékeinek felülírása az adatbázisban
                    _context.Update(permission);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PermissionExists(permission.PermissionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                // Felhasználó átírányítása a jogosultságok listájára
                return RedirectToAction(nameof(Index), new { status = !permission.IsArchived });
            }

            // Felület újra megjelenítése, amennyiben a kért értékek hibásak
            return View(permission);
        }

        /// <summary>
        /// Jogosultságok konvertálásának felületének megjelenítése
        /// </summary>
        /// <returns></returns>
        public IActionResult Convert()
        {
            return View(new PermissionConverterViewModel());
        }

        /// <summary>
        /// Bevitt szöveg jogosultságokká alakítása
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Convert(PermissionConverterViewModel model)
        {
            // Megadott értékek ellenőrzése
            if (ModelState.IsValid)
            {
                // Beviteli mező feldolgozása
                string[] inputPermissions = model.UserInput
                    .Split(';')
                    .Select(item => item.Trim())
                    .Where(item => !string.IsNullOrEmpty(item))
                    .ToArray();

                // Listák létrehozása
                HashSet<Permission> foundPermissions = new HashSet<Permission>();

                List<string> notFoundPermissions = new List<string>();

                // Bevitt értékek feldolgozása
                foreach (string inputPermission in inputPermissions)
                {

src/ISZR.Web/Views/Permissions/Convert.cshtml
@using ISZR.Web.ViewModels;

@model PermissionConverterViewModel;

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Jogosultság konvertálás";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card card-info">
                <div class="card-header">
                    <h3 class="card-title">Jogosultságok összehasonlítása a rendszerrel</h3>
                </div>

                <div class="card-body">
                    <form asp-action="Convert" asp-controller="Permissions" method="post">
                        <div class="row">
                            <div class="col-12">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Konvertálásra szánt jogosultságok</label>
                                    <span asp-validation-for="UserInput" class="text-danger"></span>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-info"><i class="fas fa-database mr-2"></i>Active Directory jogosultságok</span>
                                        </div>
                                        <input type="text" asp-for="UserInput" class="form-control" placeholder="Másold be az Active Directory jogosultságokat, amelyeket össze szeretnél hasonlítani a rendszerrel ( ;-al elválasztva )" spellcheck="false" required />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="float-right">
                                    <input type="submit" value="Konvertálás" class="btn btn-info ml-1" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

    @if (Model.FoundPermissions != null && Model.FoundPermissions.Any())
    {
        <div class="row">
            <div class="col-12 mt-4">
                <div class="card">
                    <div class="card-body p-0">
                        <table class="table table-striped">
                            <thead class="bg-success">
                                <tr>
                                    <th>Talált jogosultságok a rendszerben</th>
                                    <th>Hozzátartozó jogosultság</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var permission in Model.FoundPermissions.OrderBy(p => p.IsArchived).ThenBy(p => p.Name))
                                {
                                    <tr>
                                        <td>
                                            <span>@permission.Name</span>
                                            <br>
                                            @if (permission.IsArchived)
                                            {
                                                <span class="badge badge-danger"><i class="icon fas fa-archive mr-2"></i>Archivált jogosultság</span>
                                            }
                                            else
                                            {
                                                <span class="badge badge-success"><i class="icon fas fa-puzzle-piece mr-2"></i>Igényelhető jogosultság</span>
                                            }
                                        </td>
                                        <td>
                                            <span class="text-muted">@permission.ActiveDirectoryPermissions</span>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    }

    @if (Model.NotFoundPermissions != null && Model.NotFoundPermissions.Any())
    {
        <div class="row">
            <div class="col-12 mt-4">
                <div class="card">
                    <div class="card-body p-0">
                        <table class="table table-striped">
                            <thead class="bg-danger">
                                <tr>
                                    <th>Nem található jogosultságok a rendszerben</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var permission in Model.NotFoundPermissions)
                                {
                                    <tr>
                                        <td>
                                            <span>@permission</span>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

src/ISZR.Web/Views/Permissions/Index.cshtml
@model PaginatedList<ISZR.Web.Models.Permission>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Jogosultságok karbantartása";

    // Lista elemek betöltése
    var typeList = ViewData["TypeList"] as List<SelectListItem> ?? new List<SelectListItem>();
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <form asp-controller="Permissions" asp-action="Index" method="get">
                <div class="card card-info d-print-none">
                    <div class="card-header" data-card-widget="collapse">
                        <h3 class="card-title"><i class="icon fas fa-filter mr-2"></i>Jogosultságok szűrése</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xl-4 col-12">
                                <div class="form-group">
                                    <label>Nevezze meg a jogosultság nevét</label>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-info"><i class="fas fa-font mr-2"></i>Név</span>
                                        </div>
                                        <input name="name" type="search" class="form-control" placeholder="Keresés név alapján" value="@ViewData["name"]" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-4 col-12">
                                <div class="form-group">
                                    <label>Válassza ki a kívánt jogosultsági típust</label>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-info"><i class="fas fa-paperclip mr-2"></i>Típus</span>
                                        </div>
                                        @Html.DropDownList("type", typeList, new { @class = "form-control select2bs4" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-4 col-12">
                                <div class="form-group">
                                    <label>Válassza ki a kívánt státuszt</label>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-info"><i class="fas fa-tag mr-2"></i>Státusz</span>
                                        </div>
                                        @{
                                            var statusList = new List<SelectListItem>
                                        {
                                        new SelectListItem{ Value = "true", Text = "Igényelhető jogosultság"},
                                        new SelectListItem{ Value = "false", Text = "Archivált jogosultság"}
                                        };
                                        }
                                        @Html.DropDownList("status", statusList, new { @class = "form-control select2bs4" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-print-none">
                        <span class="float-left">
                            <a class="btn btn-default" asp-action="Create" asp-route-type="Windows"><i class="icon fab fa-windows mr-2"></i>Új Windows jogosultság létrehozása</a>
                            <a class="btn btn-default ml-2" asp-action="Create" asp-route-type="Főnix 3"><i class="icon fas fa-dove mr-2"></i>Új Főnix 3 jogosultság létrehozása</a>
                        </span>
                        <span class="float-right">
                            <a class="btn btn-default mr-2" onclick="window.print()"><i class="icon fas fa-print mr-2"></i>Lista nyomtatása</a>
                            <button type="submit" alt="Megjelenített igénylések szűrése" class="btn btn-info">Szűrés</button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0">
                    @foreach (var item in Model)
                    {
                        <div class="modal fade" id="deleteModal@(item.PermissionId)" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel@(item.PermissionId)" aria-hidden="true">
                            <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header bg-danger">
                                        <h5 class="modal-title" id="deleteModalLabel@(item.PermissionId)"><i class="fas fa-archive mr-2"></i>Archiválási állapot megváltoztatása</h5>
                                    </div>
                                    <div class="modal-body">
                                        <div>Biztosan szeretnéd <b>@item.Name</b> nevű jogosultság archiválási állapotát megváltoztatni?</div>
                                        <div>
                                            Jogosultság típusa:
                                            @if (item.Type == "Windows")
                                            {
                                                <span class="text-info font-weight-bold"><i class="icon fab fa-windows ml-1 mr-2"></i>Windows jogosultság</span>
                                            }
                                            @if (item.Type == "Főnix 3")
                                            {
                                                <span class="text-warning font-weight-bold"><i class="icon fas fa-dove ml-1 mr-2"></i>Főnix 3 jogosultság</span>
                                            }
                                        </div>
                                        <br />
                                        <div class="text-danger font-weight-bold">FIGYELEM!</div>
                                        <div class="text-muted">Archivált jogosultságot a felhasználók már nem tudnak igényelni!</div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-sign-out-alt mr-2"></i>Vissza</button>
                                        <form asp-action="Index" asp-route-id="@item.PermissionId">
                                            <input type="hidden" asp-for="@item.PermissionId" />
                                            <button type="submit" class="btn btn-danger"><i class="fas fa-archive mr-2"></i>Megváltoztatás</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    <table class="table table-striped">
                        <thead class="bg-info">
                            <tr>
                                <th>Név</th>
                                <th class="d-none d-md-table-cell">Leírás</th>
                                <th class="d-print-none"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <span>@item.Name</span>
                                        <br />
                                        @if (item.Type == "Windows")
                                        {
                                            <span class="badge badge-info"><i class="icon fab fa-windows mr-2"></i>Windows jogosultság</span>
                                        }
                                        @if (item.Type == "Főnix 3")
                                        {
                                            <span class="badge badge-warning"><i class="icon fas fa-dove mr-2"></i>Főnix 3 jogosultság</span>
                                        }
                                        @if (item.IsArchived)
                                        {
                                            <span class="badge badge-danger ml-1"><i class="icon fas fa-archive mr-2"></i>Archivált jogosultság</span>
                                        }
                                        else
                                        {
                                            <span class="badge badge-success ml-1"><i class="icon fas fa-puzzle-piece mr-2"></i>Igényelhető jogosultság</span>
                                        }
                                    </td>
                                    <td class="d-none d-md-table-cell">
                                        <span class="text-muted">@item.Description</span>
                                    </td>
                                    <td class="d-print-none">
                                        <div class="float-right">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                    <i class="fas fa-book mr-2"></i><span class="d-none d-xl-inline">Adminisztratív müveletek</span>
                                                </button>
                                                <div class="dropdown-menu">
                                                    <a asp-action="Details" asp-route-id="@item.PermissionId" class="dropdown-item"><i class="fas fa-search mr-2"></i>Megtekintés</a>
                                                    <a asp-action="Edit" asp-route-id="@item.PermissionId" class="dropdown-item"><i class="fas fa-edit mr-2"></i>Szerkesztés</a>
                                                    <div class="dropdown-divider"></div>
                                                    <a class="dropdown-item bg-danger text-white" href="#" data-toggle="modal" data-target="#deleteModal@(item.PermissionId)"><i class="fas fa-archive mr-2"></i>Archiválás</a>
                                                </div>
                                            </div>
                                        </div>

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 mt-2 mb-3">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }
            <div class="float-left ml-1 d-none d-sm-inline">
                <div class="text-muted font-italic">
                    Aktuális oldal: <span class="font-weight-bold ml-1 mr-1">@Model?.PageIndex</span>/<span class="ml-1 mr-1">@Model?.TotalPages</span><br />
                    <span class="mr-1">@ViewData["dataLength"]</span> darab jogosultság
                </div>
            </div>

            <div class="float-right d-print-none">
                <a class="btn btn-default mr-2 @prevDisabled"
                   asp-action="Index"
                   asp-route-name="@ViewData["name"]"
                   asp-route-type="@ViewData["type"]"
                   asp-route-status="@ViewData["status"]"
                   asp-route-pageNumber="@(Model?.PageIndex - 1)"><i class="fas fa-backward text-info mr-2"></i>Elöző oldal</a>

                <a class="btn btn-default @nextDisabled"
                   asp-action="Index"
                   asp-route-name="@ViewData["name"]"
                   asp-route-type="@ViewData["type"]"
                   asp-route-status="@ViewData["status"]"
                   asp-route-pageNumber="@(Model?.PageIndex + 1)">Következő oldal<i class="fas fa-forward text-info ml-2"></i></a>
            </div>
        </div>
    </div>
</div>