src/ISZR.Web/Controllers/ApplicationController.cs
using ISZR.Web.Models;
using ISZR.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ISZR.Web.Controllers
{
    /// <summary>
    /// /Application/? Controller
    /// </summary>
    [Authorize(Policy = "Administrator")]
    public class ApplicationController : Controller
    {
        private readonly DataContext _context;
        private readonly IDatabaseStatusService _databaseStatusService;
        private readonly IConfiguration _configuration;
        private readonly IHostEnvironment _environment;
        private readonly LdapService _ldapService;

        private readonly bool smtpEnable;
        private readonly bool ldapEnable;

        public ApplicationController(DataContext context, IDatabaseStatusService databaseStatusService, IConfiguration configuration, IHostEnvironment environment, LdapService ldapService)
        {
            _context = context;
            _databaseStatusService = databaseStatusService;
            _configuration = configuration;
            _environment = environment;
            _ldapService = ldapService;

            smtpEnable = configuration.GetValue<bool>("ApplicationSettings:SNMP_ENABLE");
            ldapEnable = configuration.GetValue<bool>("ApplicationSettings:LDAP_ENABLE");
        }

        /// <summary>
        /// Rendszer állapotfelméréséről jelentés
        /// </summary>
        [Authorize(Policy = "Administrator")]
        public IActionResult Index()
        {
            var viewModel = new HealthChecksViewModel { };

            // Az elmúlt 24 órában bejelentkezett felhasználók részére
            var setUserUptime = DateTime.Now.AddDays(-1);

            // Az elmúlt 1 hónap igényléseinek részére
            var setRequestTime = DateTime.Now.AddMonths(-1);

            // Adatbázis ellenőrzése
            viewModel.DatabaseStatus = _databaseStatusService.IsDatabaseOnline();

            // Bejelentkezett felhasználók statisztikája
            viewModel.LoggedUserToday = _context.Users.Count(u => u.LastLogin >= setUserUptime);

            // Szolgáltatások állapotai
            viewModel.EmailServiceStatus = smtpEnable;
            viewModel.LDAPServiceStatus = ldapEnable;
            viewModel.LDAPConnectionStatus = _ldapService.IsLdapConnectionSuccessful();

            // Igénylések statisztika
            viewModel.RequestAll = _context.Requests.Count(r => r.CreatedDateTime >= setRequestTime);
            viewModel.RequestAllDone = _context.Requests.Where(r => r.CreatedDateTime >= setRequestTime).Count(r => r.Status == "Végrehajtva");
            viewModel.RequestAllProgress = _context.Requests.Where(r => r.CreatedDateTime >= setRequestTime).Count(r => r.Status == "Folyamatban");
            viewModel.RequestAllDenied = viewModel.RequestAll - (viewModel.RequestAllDone + viewModel.RequestAllProgress);

            // Adat statisztika
            viewModel.ActiveUsers = _context.Users.Count(u => !u.IsArchived);
            viewModel.ActiveParkings = _context.Parkings.Count(p => !p.IsArchived);
            viewModel.ActiveGroups = _context.Groups.Count(g => !g.IsArchived);
            viewModel.ActiveWindowsPermission = _context.Permissions.Count(p => !p.IsArchived && p.Type == "Windows");
            viewModel.ActiveFonixPermission = _context.Permissions.Count(p => !p.IsArchived && p.Type == "Főnix 3");
            viewModel.ActivePhones = _context.Phones.Count(p => !p.IsArchived);
            viewModel.ActiveNotUsedPhone = _context.Phones.Count(p => !p.IsArchived && p.PhoneUserId == null);

            // Százalékok kiszámítása
            ViewData["donePercent"] = CalculatePercent(viewModel.RequestAllDone, viewModel.RequestAll);
            ViewData["inProgressPercent"] = CalculatePercent(viewModel.RequestAllProgress, viewModel.RequestAll);
            ViewData["deniedPercent"] = CalculatePercent(viewModel.RequestAllDenied, viewModel.RequestAll);

            // Felület megjelenítése
            return View(viewModel);
        }

        /// <summary>
        /// Appsettings értékeinek betöltése
        /// </summary>
        public IActionResult Settings()
        {
            // Értékek beolvasása a JSON fájlból
            var settings = _configuration.GetSection("ApplicationSettings").Get<ApplicationSettingsViewModel>();
            return View(settings);
        }


        /// <summary>
        /// Appsettings fájl értékeinek átírása
        /// </summary>
        /// <param name="model">appsettings értékek</param>
        [HttpPost]
        public IActionResult Settings(ApplicationSettingsViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Fájl elérési útvonalának beállítása environment típus alapján
                    var configFilePath = _environment.IsProduction() ? Path.Combine(Directory.GetCurrentDirectory(), "appsettings.json") : Path.Combine(Directory.GetCurrentDirectory(), "appsettings.Development.json");

                    // Fájl beolvasása
                    JObject configObject;
                    if (System.IO.File.Exists(configFilePath))
                    {
                        var configJson = System.IO.File.ReadAllText(configFilePath);
                        configObject = JObject.Parse(configJson);
                    }
                    else
                    {
                        configObject = new JObject();
                    }

                    // Amennyiben nem létezik, annak létrehozása
                    if (configObject["ApplicationSettings"] == null)
                    {
                        configObject["ApplicationSettings"] = new JObject();
                    }

                    // Beolvasott fájl érintett szekciójának betöltése
                    var appSettingsSection = configObject["ApplicationSettings"];

                    // Értékek frissítése
                    if (appSettingsSection != null)
                    {
                        appSettingsSection["SNMP_ENABLE"] = model.SNMP_ENABLE;
                        appSettingsSection["SNMP_SERVER"] = model.SNMP_SERVER;
                        appSettingsSection["SNMP_MAIL"] = model.SNMP_MAIL;
                        appSettingsSection["SNMP_USERNAME"] = model.SNMP_USERNAME;
                        appSettingsSection["SNMP_PASSWORD"] = model.SNMP_PASSWORD;
                        appSettingsSection["LDAP_ENABLE"] = model.LDAP_ENABLE;
                        appSettingsSection["LDAP_SERVER"] = model.LDAP_SERVER;
                        appSettingsSection["LDAP_BIND_USER"] = model.LDAP_BIND_USER;
                        appSettingsSection["LDAP_BIND_PASSWORD"] = model.LDAP_BIND_PASSWORD;
                        appSettingsSection["LDAP_BASE"] = model.LDAP_BASE;
                    }

                    // Visszaalakítás JSON formává
                    var updatedConfigJson = configObject.ToString(Formatting.Indented);

                    // Elkészült JSON elmentése
                    System.IO.File.WriteAllText(configFilePath, updatedConfigJson);
                }
                catch (Exception ex)
                {
                    // Amennyiben hiba van arról tájékoztatni
                    return View("Error", new ErrorViewModel { Message = ex.Message });
                }

                // Felhasználó tájékoztatása
                return RedirectToAction("SettingsComplete");
            }

            // Hibás model esetén újrabetöltés
            return View(model);
        }

        /// <summary>
        /// Sikeres tájékoztatás
        /// </summary>
        public IActionResult SettingsComplete()
        {
            return View();
        }

        /// <summary>
        /// Százalék kiszámítása
        /// </summary>
        /// <param name="count">Megadott érték</param>
        /// <param name="max">Maximális mennyiség</param>
        private int? CalculatePercent(int count, int max)
        {
            return (int)Math.Round((double)(100 * count) / max);
        }
    }
}

src/ISZR.Web/Controllers/PhonesController.cs
using ISZR.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CSharp.RuntimeBinder;
using System.ComponentModel;
using System.Xml.Linq;

namespace ISZR.Web.Controllers
{
    /// <summary>
    /// /Phones/? Controller
    /// </summary>
    [Authorize(Policy = "Administrator")]
    public class PhonesController : Controller
    {
        private readonly DataContext _context;

        public PhonesController(DataContext context)
        {
            _context = context;
        }

        /// <summary>
        /// PIN kódok megjelenítése
        /// </summary>
        public async Task<IActionResult> Index(string code, string user, bool status, int? pageNumber)
        {
            // Értékek beállítása
            ViewData["code"] = code;
            ViewData["user"] = user;
            ViewData["status"] = status;

            // PIN kódok listájának lekérdezése
            var dataContext = _context.Phones
                .Include(p => p.PhoneUser)
                .Include(p => p.PhoneUser.Position)
                .OrderBy(p => p.PhoneCode)
                .AsQueryable();

            // Státusz alapú szűrés
            if (status)
            {
                dataContext = dataContext.Where(r => !r.IsArchived);
            }
            else
            {
                dataContext = dataContext.Where(r => r.IsArchived);
            }

            // Név alapú szürés
            if (!string.IsNullOrEmpty(user))
            {
                dataContext = dataContext.Where(r => r.PhoneUser.DisplayName.Contains(user));
            }

            // PIN kód alapú szürés
            if (!string.IsNullOrEmpty(code))
            {
                dataContext = dataContext.Where(r => r.PhoneCode.Contains(code));
            }

            // Igénylési lista összeállítása
            await dataContext.ToListAsync();
            ViewData["dataLength"] = dataContext.Count();

            // Felület megjelenítése a kért listával
            return View(await PaginatedList<Phone>.CreateAsync(dataContext, pageNumber ?? 1));
        }

        /// <summary>
        /// PIN kód archiválási állapotának megváltoztatása
        /// </summary>
        /// <param name="id">PIN kód azonosítója</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(int? pageNumber, int? id)
        {
            // Azonosító meglétének ellenőrzése
            if (id == null || _context.Phones == null) return NotFound();

            // PIN kód megkeresése az adatbázisban
            var pin = await _context.Phones.FirstOrDefaultAsync(m => m.PhoneId == id);

            // PIN kód meglétének ellenőrzése
            if (pin == null) return NotFound();

            try
            {
                // Archiválás értékének módosítása
                pin.IsArchived = !pin.IsArchived;

                // PIN kód értékeinek frissítése az adatbázisban
                _context.Update(pin);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PhoneExists(pin.PhoneId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            // Felület újra megjelenítése
            return RedirectToAction(nameof(Index), new {status = !pin.IsArchived});
        }

        /// <summary>
        /// PIN kód létrehozásának felülete
        /// </summary>
        public IActionResult Create()
        {
            // Lista elemek betöltése
            try
            {
                ViewData["PhoneUserId"] = new SelectList(_context.Users.Where(u => !u.IsArchived).OrderBy(u => u.DisplayName).Select(u => new
                {
                    u.UserId,
                    DisplayText = $"{u.DisplayName} bv.{u.Rank.ToLower()} ({u.Position.Name})"
                }), "UserId", "DisplayText");
            }
            catch (RuntimeBinderException ex)
            {
                Console.WriteLine(ex.Message);
            }

            // Felület megjelenítése
            return View();
        }

        /// <summary>
        /// PIN kód létrehozása a rendszerben
        /// </summary>
        /// <param name="phone">Megadott PIN kód adatai</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PhoneId,PhoneCode,PhoneUserId,IsArchived")] Phone phone)
        {
            // Megadott értékek ellenőrzése
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(phone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhoneExists(phone.PhoneId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                // Felhasználó átirányítása a parkolási engedélyek listájára
                return RedirectToAction(nameof(Index), new {status = true});
            }

            // Lista elemek betöltése
            try
            {
                ViewData["PhoneUserId"] = new SelectList(_context.Users.Where(u => !u.IsArchived).OrderBy(u => u.DisplayName).Select(u => new
                {
                    u.UserId,
                    DisplayText = $"{u.DisplayName} bv.{u.Rank.ToLower()} ({u.Position.Name})"
                }), "UserId", "DisplayText");
            }
            catch (RuntimeBinderException ex)
            {
                Console.WriteLine(ex.Message);
            }

            // Felület megjelenítése amennyiben hibásan lettek megadva az adatok
            return View(phone);
        }

        /// <summary>
        /// PIN kód szerkesztésének felülete
        /// </summary>
        /// <param name="id">PIN kód azonosítója</param>
        public async Task<IActionResult> Edit(int? id)
        {
            // PIN kód azonosítójánakmeglétének ellenőrzése
            if (id == null || _context.Phones == null) return NotFound();

            // Kért PIN kód megkeresése az adatbázisban
            var phone = await _context.Phones.FindAsync(id);

            // PIN kód meglétének ellenőrzése
            if (phone == null) return NotFound();

            // Lista elemek betöltése
            try
            {
                ViewData["PhoneUserId"] = new SelectList(_context.Users.Where(u => !u.IsArchived).OrderBy(u => u.DisplayName).Select(u => new
                {
                    u.UserId,
                    DisplayText = $"{u.DisplayName} bv.{u.Rank.ToLower()} ({u.Position.Name})"
                }), "UserId", "DisplayText");
            }
            catch (RuntimeBinderException ex)
            {
                Console.WriteLine(ex.Message);
            }

            // Felület megjelenítése a kért PIN kód adataival
            return View(phone);
        }

        /// <summary>
        /// PIN kód adatainak szerkesztése
        /// </summary>
        /// <param name="id">PIN kód azonosítója</param>
        /// <param name="phone">Megadott PIN kód új értékei</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PhoneId,PhoneCode,PhoneUserId,IsArchived")] Phone phone)
        {
            // Azonosító meglétének ellenőrzése
            if (id != phone.PhoneId) return NotFound();

            // Megadott értékek ellenőrzése
            if (ModelState.IsValid)
            {
                try
                {
                    // PIN kód adatainak felülírása
                    _context.Update(phone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PhoneExists(phone.PhoneId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                // Felhasználó átirányítása a PIN kódok listájára
                return RedirectToAction(nameof(Index), new {status = !phone.IsArchived});
            }

            // Lista elemek betöltése
            try
            {
                ViewData["PhoneUserId"] = new SelectList(_context.Users.Where(u => !u.IsArchived).OrderBy(u => u.DisplayName).Select(u => new
                {
                    u.UserId,
                    DisplayText = $"{u.DisplayName} bv.{u.Rank.ToLower()} ({u.Position.Name})"
                }), "UserId", "DisplayText");
            }
            catch (RuntimeBinderException ex)
            {
                Console.WriteLine(ex.Message);
            }

            // Felület megjelenítése amennyiben hibás adatokat tartalmaz
            return View(phone);
        }

        /// <summary>
        /// PIN kód meglétének ellenőrzése
        /// </summary>
        /// <param name="id">PIN kód azonosítója</param>
        /// <returns>Létezik e az adott PIN kód (igaz/hamis)</returns>
        private bool PhoneExists(int id)
        {
            return (_context.Phones?.Any(e => e.PhoneId == id)).GetValueOrDefault();
        }
    }
}

src/ISZR.Web/Views/Application/Index.cshtml
@using ISZR.Web.ViewModels;

@model HealthChecksViewModel;

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Rendszer állapotfelmérése";
    var healthcheck = $"{Context.Request.Scheme}://{Context.Request.Host}/healthz";

}

<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-4">
            <div class="info-box bg-default">
                <span class="info-box-icon"><i class="fas fa-database"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Adatbázis</span>
                    @if (Model.DatabaseStatus)
                    {
                        <span class="info-box-number text-success font-weight-bold"><i class="icon fas fa-signal mr-2"></i>Elérhető</span>
                    }
                    else
                    {
                        <span class="info-box-number text-danger font-weight-bold"><i class="icon fas fa-exclamation-triangle mr-2"></i>Nem elérhető</span>
                    }
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="info-box bg-default">
                <span class="info-box-icon"><i class="fas fa-server"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Active Directory szolgáltatás</span>
                    @if (Model.LDAPServiceStatus && Model.LDAPConnectionStatus)
                    {
                        <a class="info-box-number text-success font-weight-bold" asp-controller="Application" asp-action="Settings"><i class="icon fas fa-signal mr-2"></i>Sikeres csatlakozva</a>
                    }
                    else if (Model.LDAPServiceStatus && !Model.LDAPConnectionStatus)
                    {
                        <a class="info-box-number text-danger font-weight-bold" asp-controller="Application" asp-action="Settings"><i class="icon fas fa-exclamation-triangle mr-2"></i>Sikertelen csatlakozás</a>
                    }
                    else
                    {
                        <a class="info-box-number text-danger font-weight-bold" asp-controller="Application" asp-action="Settings"><i class="icon fas fa-power-off mr-2"></i>Kikapcsolva</a>
                    }
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="info-box bg-default">
                <span class="info-box-icon"><i class="fas fa-envelope"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">E-mail értesítési szolgáltatás</span>
                    @if (Model.EmailServiceStatus)
                    {
                        <a class="info-box-number text-success font-weight-bold" asp-controller="Application" asp-action="Settings"><i class="icon fas fa-power-off mr-2"></i>Bekapcsolva</a>
                    }
                    else
                    {
                        <a class="info-box-number text-danger font-weight-bold" asp-controller="Application" asp-action="Settings"><i class="icon fas fa-power-off mr-2"></i>Kikapcsolva</a>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h4 class="m-2">Felhasználókkal kapcsolatos</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="info-box bg-default">
                <span class="info-box-icon"><i class="fas fa-building"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Aktív felhasználók az elmúlt időszakban</span>
                    <div class="info-box-number text-muted">
                        <a asp-controller="Users" asp-action="Online" class="mr-2 text-success font-weight-bold"><i class="icon fas fa-user mr-2"></i>@Model.LoggedUserToday</a>
                        <span class="mr-2 text-muted">/</span>
                        <a asp-controller="Users" asp-action="Index" asp-route-status="True" class="text-muted"><i class="icon fas fa-users mr-2"></i>@Model.ActiveUsers</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="info-box bg-default">
                <span class="info-box-icon"><i class="fas fa-parking"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Jelenleg aktív parkolási engedélyek</span>
                    <div class="info-box-number">
                        <a asp-controller="Parkings" asp-action="Index" asp-route-status="True" class="text-success font-weight-bold"><i class="icon fas fa-car-side mr-2"></i>@Model.ActiveParkings</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h4 class="m-2">Felhasználók számára igényelhető</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-4">
            <div class="info-box bg-default">
                <span class="info-box-icon"><i class="fas fa-users-cog"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Jogosultsági csoport</span>
                    <div class="info-box-number">
                        <a asp-controller="Groups" asp-action="Index" asp-route-status="True" class="text-success font-weight-bold"><i class="icon fas fa-user-friends mr-2"></i>@Model.ActiveGroups</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="info-box bg-default">
                <span class="info-box-icon"><i class="fas fa-key"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text">Jogosultság</span>
                    <div class="info-box-number font-weight-bold text-muted">
                        <a asp-controller="Permissions" asp-action="Index" asp-route-status="True" asp-route-type="Windows" class="mr-2 text-info"><i class="icon fab fa-windows mr-2"></i>@Model.ActiveWindowsPermission</a>
                        <span class="mr-2 text-muted">/</span>
                        <a asp-controller="Permissions" asp-action="Index" asp-route-status="True" asp-route-type="Főnix 3" class="text-warning"><i class="icon fas fa-dove mr-2"></i>@Model.ActiveFonixPermission</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-4">
            <div class="info-box bg-default">
                <span class="info-box-icon"><i class="fas fa-phone-square-alt"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text text-muted">PIN Kód</span>
                    <div class="info-box-number">
                        <a asp-controller="Phones" asp-action="Index" asp-route-status="True" class="text-success font-weight-bold"><i class="icon fas fa-phone mr-2"></i>@Model.ActiveNotUsedPhone</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h4 class="m-2">Az elmúlt 1 hónap igényléseinek statisztikái</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card card-info">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <div class="progress-group">
                                <span class="progress-text">Végrehajtva</span>
                                <span class="float-right">@Model.RequestAllDone darab igénylés (@ViewData["donePercent"]%)</span>
                                <div class="progress progress-sm">
                                    <div class="progress-bar bg-success" style="width: @ViewData["donePercent"]%"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="progress-group">
                                <span class="progress-text">Folyamatban lévő</span>
                                <span class="float-right">@Model.RequestAllProgress darab igénylés (@ViewData["inProgressPercent"]%)</span>
                                <div class="progress progress-sm">
                                    <div class="progress-bar bg-warning" style="width: @ViewData["inProgressPercent"]%"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="progress-group">
                                <span class="progress-text">Elutasítva</span>
                                <span class="float-right">@Model.RequestAllDenied darab igénylés (@ViewData["deniedPercent"]%)</span>
                                <div class="progress progress-sm">
                                    <div class="progress-bar bg-danger" style="width: @ViewData["deniedPercent"]%"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/ISZR.Web/Views/Application/SettingsComplete.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Beállítások megtörténtek";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card card-success">
                <div class="card-header">
                    <h3 class="card-title">A rendszer beállításai sikeresen elmentve</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <div>Az alkalmazást újra kell indítani, hogy az új beállításokkal tudjanak működni.</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>