src/ISZR.Web/Controllers/ClassesController.cs
using ISZR.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ISZR.Web.Controllers
{
    /// <summary>
    /// /Classes/? Controller
    /// </summary>
    [Authorize(Policy = "Administrator")]
    public class ClassesController : Controller
    {
        private readonly DataContext _context;

        public ClassesController(DataContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Osztályok listájának megjelenítése
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index(string name, string user, bool status, int? pageNumber)
        {
            // Értékek beállítása
            ViewData["name"] = name;
            ViewData["user"] = user;
            ViewData["status"] = status;

            // Osztályok listájának lekérdezése
            var dataContext = _context.Classes
                .Include(c => c.Authorizer)
                .Include(c => c.Authorizer.Position)
                .OrderBy(c => c.Name)
                .AsQueryable();

            // Státusz alapú szűrés
            if (status)
            {
                dataContext = dataContext.Where(r => !r.IsArchived);
            }
            else
            {
                dataContext = dataContext.Where(r => r.IsArchived);
            }

            // Név alapú szürés
            if (!string.IsNullOrEmpty(name))
            {
                dataContext = dataContext.Where(r => r.Name.Contains(name));
            }

            // Engedélyező neve alapú szürés
            if (!string.IsNullOrEmpty(user))
            {
                dataContext = dataContext.Where(r => r.Authorizer.DisplayName.Contains(user));
            }

            // Igénylési lista összeállítása
            await dataContext.ToListAsync();
            ViewData["dataLength"] = dataContext.Count();

            // Felület megjelenítése a kért listával
            return View(await PaginatedList<Class>.CreateAsync(dataContext, pageNumber ?? 1));
        }

        /// <summary>
        /// Osztály archiválási állapotának megváltoztatása
        /// </summary>
        /// <param name="id">Osztály azonosítója</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(int? pageNumber, int? id)
        {
            // Azonosító meglétének ellenőrzése
            if (id == null || _context.Classes == null) return NotFound();

            // Osztály megkeresése az adatbázisban
            var @class = await _context.Classes
                .FirstOrDefaultAsync(m => m.ClassId == id);

            // Osztály meglétének ellenőrzése
            if (@class == null) return NotFound();

            try
            {
                // Archiválás értékének módosítása
                @class.IsArchived = !@class.IsArchived;

                // Osztály értékeinek frissítése az adatbázisban
                _context.Update(@class);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ClassExists(@class.ClassId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            // Felület újra megjelenítése
            return RedirectToAction(nameof(Index), new {status = !@class.IsArchived});
        }

        /// <summary>
        /// Osztály létrehozásának felülete
        /// </summary>
        public IActionResult Create()
        {
            // Lista elem betöltése
            ViewData["AuthorizerId"] = new SelectList(_context.Users.Where(u => !u.IsArchived).OrderBy(u => u.DisplayName).Select(u => new
            {
                u.UserId,
                DisplayText = $"{u.DisplayName} bv.{u.Rank.ToLower()} ({u.Position.Name})"
            }), "UserId", "DisplayText");

            // Felület megjelenítése
            return View();
        }

        /// <summary>
        /// Osztály létrehozása az adatbázisban
        /// </summary>
        /// <param name="class">Osztály megadott adatai</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClassId,Name,AuthorizerId,IsArchived")] Class @class)
        {
            // Megadott értékek ellenőrzése
            if (ModelState.IsValid)
            {
                try
                {
                    // Osztály hozzáadása az adatbázishoz
                    _context.Add(@class);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassExists(@class.ClassId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                // Felhasználó átírányítása az osztályok listájára
                return RedirectToAction(nameof(Index), new {status = true});
            }

            // Lista elem betöltése
            ViewData["AuthorizerId"] = new SelectList(_context.Users.Where(u => !u.IsArchived).OrderBy(u => u.DisplayName).Select(u => new
            {
                u.UserId,
                DisplayText = $"{u.DisplayName} bv.{u.Rank.ToLower()} ({u.Position.Name})"
            }), "UserId", "DisplayText");

            // Felület újra megjelenítése, amennyiben hibás értékeket adott meg
            return View(@class);
        }

        /// <summary>
        /// Osztály szerkesztésének felülete
        /// </summary>
        /// <param name="id">Osztály azonosítója</param>
        public async Task<IActionResult> Edit(int? id)
        {
            // Azonosító meglétének ellenőrzése
            if (id == null || _context.Classes == null) return NotFound();

            // Osztály megkeresése az adatbázisban
            var @class = await _context.Classes.FindAsync(id);

            // Osztály meglétének ellenőrzése
            if (@class == null) return NotFound();

            // Lista elem betöltése
            ViewData["AuthorizerId"] = new SelectList(_context.Users.Where(u => !u.IsArchived).OrderBy(u => u.DisplayName).Select(u => new
            {
                u.UserId,
                DisplayText = $"{u.DisplayName} bv.{u.Rank.ToLower()} ({u.Position.Name})"
            }), "UserId", "DisplayText");

            // Felület megjelenítése a kért osztály adataival
            return View(@class);
        }

        /// <summary>
        /// Ostály adatainak felülírása az adatbázisban
        /// </summary>
        /// <param name="id">Osztály azonosítja</param>
        /// <param name="class">Osztály megadott új értékei</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClassId,Name,AuthorizerId,IsArchived")] Class @class)
        {
            // Azonosító meglétének ellenőrzése
            if (id != @class.ClassId) return NotFound();

            // Megadott értékek ellenőrzése
            if (ModelState.IsValid)
            {
                try
                {
                    // Osztály hozzáadása az adatbázishoz
                    _context.Update(@class);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassExists(@class.ClassId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                // Felhasználó átírányítása az osztályok listájára
                return RedirectToAction(nameof(Index), new {status = !@class.IsArchived});
            }

            // Lista elem betöltése
            ViewData["AuthorizerId"] = new SelectList(_context.Users.Where(u => !u.IsArchived).OrderBy(u => u.DisplayName).Select(u => new
            {
                u.UserId,
                DisplayText = $"{u.DisplayName} bv.{u.Rank.ToLower()} ({u.Position.Name})"
            }), "UserId", "DisplayText");

            // Felület újra megjelenítése, amennyiben hibás értékeket adott meg
            return View(@class);
        }

        /// <summary>
        /// Osztály létezésének ellenőrzése
        /// </summary>
        /// <param name="id">Osztály azonosítója</param>
        /// <returns>Létezik e az osztály (igaz/hamis)</returns>
        private bool ClassExists(int id)
        {
            return _context.Classes.Any(e => e.ClassId == id);
        }
    }
}

src/ISZR.Web/Views/Classes/Create.cshtml
@model ISZR.Web.Models.Class

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Új osztály vagy csoport létrehozása";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card card-success">
                <div class="card-header">
                    <h3 class="card-title">Osztályhoz vagy csoporthoz tartozó adatok beállítása</h3>
                </div>
                <div class="card-body">
                    <form asp-action="Create" onsubmit="submitButton.disabled = true; return true;">
                        <div class="row">
                            <div class="col-12">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 col-xl-6">
                                <div class="form-group">
                                    <label>Nevezze meg az osztály vagy csoport nevét</label><span class="text-danger font-weight-bold ml-1">*</span>
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-success"><i class="fas fa-users mr-2"></i>Név</span>
                                        </div>
                                        <input type="text" asp-for="Name" class="form-control" placeholder="Osztály vagy csoport megnevezése" spellcheck="true" required />
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-xl-6">
                                <div class="form-group">
                                    <label>Válassza ki az engedélyező személyt</label><span class="text-danger font-weight-bold ml-1">*</span>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-success"><i class="fas fa-signature mr-2"></i>Engedélyező</span>
                                        </div>
                                        <select asp-for="AuthorizerId" class="form-control select2bs4" asp-items="ViewBag.AuthorizerId">
                                            <option value="">Nincs</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="float-left">
                                    <div class="custom-control custom-checkbox">
                                        <input class="custom-control-input" type="checkbox" id="agreeToTerms" name="agreeToTerms" required />
                                        <label class="custom-control-label" for="agreeToTerms">
                                            Minden kötelező mezőt (<span class="text-danger font-weight-bold">*</span>) kitöltöttem, és a megadott adatok helyesek.
                                        </label>
                                    </div>
                                </div>
                                <div class="float-right">
                                    <a onclick="history.back()" class="btn btn-secondary"><i class="icon fas fa-sign-out-alt mr-2"></i>Vissza</a>
                                    <input id="submitButton" name="submitButton" type="submit" value="Osztály vagy csoport létrehozása" class="btn btn-success ml-1" disabled />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/ISZR.Web/Views/Classes/Edit.cshtml
@model ISZR.Web.Models.Class

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Osztály vagy csoport szerkesztése";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card card-warning">
                <div class="card-header">
                    <h3 class="card-title">Osztályhoz vagy csoporthoz tartozó adatok szerkesztése</h3>
                </div>
                <div class="card-body">
                    <form asp-action="Edit" onsubmit="submitButton.disabled = true; return true;">
                        <div class="row">
                            <div class="col-12">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            </div>
                        </div>
                        <input type="hidden" asp-for="ClassId" />
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label>Nevezze meg az osztály vagy csoport nevét</label><span class="text-danger font-weight-bold ml-1">*</span>
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-warning"><i class="fas fa-users mr-2"></i>Név</span>
                                        </div>
                                        <input type="text" asp-for="Name" class="form-control" placeholder="Osztály vagy csoport megnevezése" spellcheck="true" required />
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label>Válassza ki az engedélyező személyt</label><span class="text-danger font-weight-bold ml-1">*</span>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-warning"><i class="fas fa-signature mr-2"></i>Engedélyező</span>
                                        </div>
                                        <select asp-for="AuthorizerId" class="form-control select2bs4" asp-items="ViewBag.AuthorizerId">
                                            <option value="">Nincs</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <div class="float-left">
                                    <div class="custom-control custom-checkbox">
                                        <input class="custom-control-input" type="checkbox" id="agreeToTerms" name="agreeToTerms" required />
                                        <label class="custom-control-label" for="agreeToTerms">
                                            Minden kötelező mezőt (<span class="text-danger font-weight-bold">*</span>) kitöltöttem, és a megadott adatok helyesek.
                                        </label>
                                    </div>
                                </div>
                                <div class="float-right">
                                    <a onclick="history.back()" class="btn btn-secondary"><i class="icon fas fa-sign-out-alt mr-2"></i>Vissza</a>
                                    <input id="submitButton" type="submit" value="Osztály vagy csoport szerkesztése" class="btn btn-warning ml-1" disabled />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/ISZR.Web/Views/Classes/Index.cshtml
@model PaginatedList<ISZR.Web.Models.Class>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewData["Title"] = "Osztályok és csoportok karbantartása";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <form asp-controller="Classes" asp-action="Index" method="get">
                <div class="card card-info d-print-none">
                    <div class="card-header" data-card-widget="collapse">
                        <h3 class="card-title"><i class="icon fas fa-filter mr-2"></i>Osztályok és csoportok szűrése</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 col-xl-4">
                                <div class="form-group">
                                    <label>Nevezze meg az osztály vagy csoport nevét</label>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-info"><i class="fas fa-font mr-2"></i>Név</span>
                                        </div>
                                        <input name="name" type="search" class="form-control" placeholder="Keresés név alapján" value="@ViewData["name"]" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-xl-4">
                                <div class="form-group">
                                    <label>Nevezze meg az engedélyező nevét</label>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-info"><i class="fas fa-font mr-2"></i>Engedélyező neve</span>
                                        </div>
                                        <input name="user" type="search" class="form-control" placeholder="Keresés engedélyező neve alapján" value="@ViewData["user"]" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-xl-4">
                                <div class="form-group">
                                    <label>Válassza ki a kívánt státuszt</label>
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text bg-info"><i class="fas fa-tag mr-2"></i>Státusz</span>
                                        </div>
                                        @{
                                            var statusList = new List<SelectListItem>
                                        {
                                        new SelectListItem{ Value = "true", Text = "Kiválasztható osztály"},
                                        new SelectListItem{ Value = "false", Text = "Archivált osztály"}
                                        };
                                        }
                                        @Html.DropDownList("status", statusList, new { @class = "form-control select2bs4" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-print-none">
                        <span class="float-left">
                            <a class="btn btn-default" asp-action="Create"><i class="icon fas fa-users mr-2"></i>Új osztály vagy csoport létrehozása</a>
                        </span>
                        <span class="float-right">
                            <a class="btn btn-default mr-2" onclick="window.print()"><i class="icon fas fa-print mr-2"></i>Lista nyomtatása</a>
                            <button type="submit" alt="Megjelenített igénylések szűrése" class="btn btn-info">Szűrés</button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body p-0">
                    @foreach (var item in Model)
                    {
                        <div class="modal fade" id="deleteModal@(item.ClassId)" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel@(item.ClassId)" aria-hidden="true">
                            <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                                <div class="modal-content">
                                    <div class="modal-header bg-danger">
                                        <h5 class="modal-title" id="deleteModalLabel@(item.ClassId)"><i class="fas fa-archive mr-2"></i>Archiválási állapot megváltoztatása</h5>
                                    </div>
                                    <div class="modal-body">
                                        <div>Biztosan szeretnéd <b>@item.Name</b> nevű osztály archiválási állapotát megváltoztatni?</div>
                                        <br />
                                        <div class="text-danger font-weight-bold">FIGYELEM!</div>
                                        <div class="text-muted">Archivált osztályt a felhasználók nem tudnak kiválasztani, azonban aki már használja annak nem kerül törlésre!</div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="icon fas fa-sign-out-alt mr-2"></i>Vissza</button>
                                        <form asp-action="Index" asp-route-id="@item.ClassId" method="post">
                                            <input type="hidden" asp-for="@item.ClassId" />
                                            <button type="submit" class="btn btn-danger"><i class="fas fa-archive mr-2"></i>Megváltoztatás</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    <table class="table table-striped">
                        <thead class="bg-info">
                            <tr>
                                <th>Név</th>
                                <th>Engedélyező személy</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <span>@item.Name</span><br />
                                        @if (item.IsArchived)
                                        {
                                            <span class="badge badge-danger"><i class="icon fas fa-archive mr-2"></i>Archivált osztály</span>
                                        }
                                        else
                                        {
                                            <span class="badge badge-success"><i class="icon fas fa-user-friends mr-2"></i>Kiválasztható osztály</span>
                                        }
                                    </td>
                                    <td>
                                        @if (item.Authorizer != null)
                                        {
                                            <span>@item.Authorizer?.DisplayName bv. @item.Authorizer?.Rank?.ToLower()</span>
                                            <br />
                                            <span class="badge badge-info">@item.Authorizer?.Position?.Name</span>
                                        }
                                        else
                                        {
                                            <span class="text-danger font-weight-bold"><i class="icon fas fa-exclamation-triangle mr-2"></i>Engedélyező nincs beállítva</span>
                                        }
                                    </td>
                                    <td class="d-print-none">
                                        <div class="float-right">
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                    <i class="fas fa-book mr-2"></i><span class="d-none d-xl-inline">Adminisztratív müveletek</span>
                                                </button>
                                                <div class="dropdown-menu">
                                                    <a asp-action="Edit" asp-route-id="@item.ClassId" class="dropdown-item"><i class="fas fa-edit mr-2"></i>Szerkesztés</a>
                                                    <div class="dropdown-divider"></div>
                                                    <a class="dropdown-item bg-danger text-white" href="#" data-toggle="modal" data-target="#deleteModal@(item.ClassId)"><i class="fas fa-archive mr-2"></i>Archiválás</a>
                                                </div>
                                            </div>

                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 mt-2 mb-3">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }
            <div class="float-left ml-1 d-none d-sm-inline">
                <div class="text-muted font-italic">
                    Aktuális oldal: <span class="font-weight-bold ml-1 mr-1">@Model?.PageIndex</span>/<span class="ml-1 mr-1">@Model?.TotalPages</span><br />
                    <span class="mr-1">@ViewData["dataLength"]</span> darab osztály
                </div>
            </div>

            <div class="float-right d-print-none">
                <a class="btn btn-default mr-2 @prevDisabled"
                   asp-action="Index"
                   asp-route-name="@ViewData["name"]"
                   asp-route-user="@ViewData["user"]"
                   asp-route-status="@ViewData["status"]"
                   asp-route-pageNumber="@(Model?.PageIndex - 1)"><i class="fas fa-backward text-info mr-2"></i>Elöző oldal</a>

                <a class="btn btn-default @nextDisabled"
                   asp-action="Index"
                   asp-route-name="@ViewData["name"]"
                   asp-route-user="@ViewData["user"]"
                   asp-route-status="@ViewData["status"]"
                   asp-route-pageNumber="@(Model?.PageIndex + 1)">Következő oldal<i class="fas fa-forward text-info ml-2"></i></a>
            </div>
        </div>
    </div>
</div>